Table customers {
  customer_id int [pk, increment]
  first_name varchar
  last_name varchar
  email varchar [unique]
  gender varchar
  date_of_birth date
  city varchar
  state varchar
  country varchar
  created_at timestamp
}

Table stores {
  store_id int [pk, increment]
  store_name varchar
  city varchar
  state varchar
  country varchar
  opened_date date
}

Table products {
  product_id int [pk, increment]
  product_name varchar
  category varchar
  sub_category varchar
  price decimal(10,2)
  manufacturer varchar
}

Table dates {
  date_id int [pk, increment]
  full_date date
  day int
  month int
  quarter int
  year int
  day_of_week varchar
  is_weekend boolean
}

Table promotions {
  promotion_id int [pk, increment]
  promotion_name varchar
  start_date date
  end_date date
  discount_percent decimal(5,2)
  description varchar
}

Table sales_fact {
  sale_id bigint [pk, increment]
  customer_id int
  store_id int
  product_id int
  date_id int
  promotion_id int
  quantity int
  unit_price decimal(10,2)
  total_amount decimal(12,2)
}

Ref: customers.customer_id < sales_fact.customer_id
Ref: stores.store_id < sales_fact.store_id
Ref: products.product_id < sales_fact.product_id
Ref: dates.date_id < sales_fact.date_id
Ref: promotions.promotion_id < sales_fact.promotion_id
